spring:
  datasource:
    url: jdbc:sqlserver://db:1433;databaseName=GoldenBowl;encrypt=true;trustServerCertificate=true
    username: sa
    password: GoldenBowl123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

  # 郵件設定 (可選)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 伺服器設定
server:
  port: 8080
  servlet:
    context-path: /

# 日誌設定
logging:
  level:
    tw.com.ispan.eeit: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

# CORS 設定
cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "http://localhost:3002"
    - "http://localhost:80"
    - "http://localhost:443"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
