jwt:
  token:
    expire: 10

spring:
  application:
    name: GoldenBowl


  output:
    ansi:
      enabled: always

  #設定資料庫執行環境
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # url: jdbc:sqlserver://192.168.36.81:5433;database=java;trustServerCertificate=true
    url: jdbc:sqlserver://localhost:1433;database=back;trustServerCertificate=true
    username: sa
    password: P@ssw0rd

  # 設定JPA
  jpa:
    show-sql: true 
    #顯示資料庫語法
    database-platform: org.hibernate.dialect.SQLServerDialect # 讓java語法轉為SQL語法
    hibernate:
      ddl-auto: update
      #update 更新java entity時，也會創建
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        #會自動捕捉entity讓你不用備註column
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #連結資料庫讓名稱與java相同

